from typing import Optional

class PyAVLTree:
    def __init__(self) -> None: ...
    def insert(self, value: float): ...
    def insert_all(self, value: list[float]): ...
    def remove(self, value: float) -> bool: ...
    def contains(self, value: float) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def rank(self, value: float) -> int: ...
    def select(self, rank: int) -> Optional[float]: ...
